collections:
  landingPages:
    output: true


defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: pages
      permalink: pretty
  -
    scope:
      path: ""
      type: landingPages
    values:
      layout: landingPages
      permalink: pretty
